config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => "Contact Form",
        :to => "jchristopher.cato@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_image :string
#  slug       :string
#

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true, length:{minimum: 3}
  validates :body, presence: true

  mount_uploader :post_image, PostImageUploader


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #authenticate_user! is from the devise gem.
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image, :post_image_url, :remote_image_url, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/create.html.erb
<h1>Hey!</h1>

<div>
  <h1>Thanks! You'll be hearing from me soon!</h1>
  <p>Talk to you soon!</p>
</div>

app/views/contacts/new.html.erb
<h1>Hello!</h1>
  <div id="contact-page">
    <%= form_for @contact do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, :class => "form-control" %>
      <br>

      <%= f.label :email %><br>
      <%= f.email_field :email, required: true, :class => "form-control" %>
      <br>

      <%= f.label :message %><br>
      <%= f.text_area :message, required: true, :class => "form-control" %>
      <br>

      <%= f.hidden_field :nickname, hint: "blank" %>

      <%= f.submit 'Send', class: "button" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>{JohnCato}</title>
  <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=PT+Mono' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div>
        <a class="navbar-brand name" href="#">< ></a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "My Blog", root_path, :class => "top" %></li>
        <li><%= link_to "About", about_path, :class => "top" %></li>
        <li><%= link_to "Github", 'https://github.com/cato-hga', :class => "top" %></li>
        <li><%= link_to '<i class="fa fa-commenting-o aria-hidden= true"></i>'.html_safe, new_contact_path %></li>
      </ul>
    </div>
  </nav>
  <% if user_signed_in? %>
    <div><br>
      <button type="button" class="btn btn-default">
        <%= link_to "New Post", new_post_path %>
      </button>
      <button type="button" class="btn btn-default">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </button><br><br>
    </div>
  <% else %>
    <div class="text-center">
      <h1 class="n_logged_in"><strong>Software developer | Husband | Coffee fanatic | Tampa, FL</strong></h1>
    </div>
  <% end %>
    <div class="container-fluid">
      <div class="col-sm-8 col-height">
        <%= yield %>
      </div>
      <div class="col-sm-4">
        <%= render 'posts/connect' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class='move'>
    <%= image_tag("cato.jpg",:id => "circle-img")%>
  <h1> About John</h1>
  <p>Thanks for visiting my site! My name is John Cato and I'm a software developer specializing in Ruby/Rails. I live in sunny Tampa, FL with my beautiful wife.</p>
  <ul class="text-left">
     <strong><p><%= link_to "Hobbies", "#", id: "currenthobbies-link"%></p></strong>
    <div class="hobbies_hide">
      <p>I enjoy:</p>
      <li>Ruby/Rails</li>
      <li>Learning new technologies</li>
      <li>Podcasts</li>
      <li>Coffee brewed with a Chemex</li>
    </div>
  </ul>
  <ul class="text-left">
    <strong><p><%= link_to "Learning", "#", id: "currentlylearning-link"  %></p></strong>
    <div class="pages_hide">
      <p>Currently learning:</p>
      <li>Elixir & Phoenix</li>
      <li>Emberjs</li>
    </div>
  </ul>
  <ul class="text-left">
    <p>Feel free to shoot me an <%= link_to "email", "mailto:jchristopher.cato@gmail.com", class:"email" %> or use the contact form if you want to get in touch.</p>
  </ul>
</div>

app/views/posts/_connect.html.erb
<div>
  <div class="text-center">
    <h1>Follow Me</h1>
  </div>
  <div class="follow-me-icon text-center">
    <a href="https://www.linkedin.com/in/johncato813"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
    <a href="https://twitter.com/cato_hga"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    <a href="https://github.com/cato-hga"><i class="fa fa-github-square" aria-hidden="true"></i></a>
    <!--<a href="mailto:jchristopher.cato@gmail.com"><i class="fa fa-envelope" aria-hidden="true"></i></a>-->
  </div>
</div>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
   var disqus_shortname = 'johncato';
   var disqus_identifier = '<%= @post.id%>';
   var disqus_title = '<%= @post.title%>';
   var disqus_url = '<%= url_for([@post, {only_path: false}])%>';

  (function() {  // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = '//johncato.disqus.com/embed.js';

    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
  <div class="page_wrapper">
    <%= form_for @post, :html => {:multipart => true } do |f| %>
        <% if @post.errors.any? %>
            <div>
              <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <p class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => "form-control" %>
        </p>
        <p>
          <%= f.file_field :post_image %>
        </p>
        <p>
          <%= f.label :remote_post_image_url, "or load with URL" %><br>
          <%= f.text_field :remote_post_image_url %>
        </p>
        <p class="form-group">
          <%= f.label :body %><br>
          <%= f.text_area :body, id: "wysiwyg" %>
        </p>
        <p>
          <%= f.submit %>
        </p>
    <% end %>
  </div>
<script>
  $('#wysiwyg').froalaEditor({
    toolbarInline: false,
    heightMin: '200px',
    charCounterCount: true,
    htmlAllowedTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'a', 'embed', 'iframe', 'video'],
    htmlAllowedAttrs: ['accept', 'accept-charset', 'accesskey', 'action', 'align', 'alt', 'async', 'autocomplete', 'autofocus', 'autoplay', 'autosave', 'background', 'bgcolor', 'border', 'charset', 'cellpadding', 'cellspacing', 'checked', 'cite', 'class', 'color', 'cols', 'colspan', 'content', 'contenteditable', 'contextmenu', 'controls', 'coords', 'data', 'data-.*', 'datetime', 'default', 'defer', 'dir', 'dirname', 'disabled', 'download', 'draggable', 'dropzone', 'enctype', 'for', 'form', 'formaction', 'headers', 'height', 'hidden', 'high', 'href', 'hreflang', 'http-equiv', 'icon', 'id', 'ismap', 'itemprop', 'keytype', 'kind', 'label', 'lang', 'language', 'list', 'loop', 'low', 'max', 'maxlength', 'media', 'method', 'min', 'multiple', 'name', 'novalidate', 'open', 'optimum', 'pattern', 'ping', 'placeholder', 'poster', 'preload', 'pubdate', 'radiogroup', 'readonly', 'rel', 'required', 'reversed', 'rows', 'rowspan', 'sandbox', 'scope', 'scoped', 'scrolling', 'seamless', 'selected', 'shape', 'size', 'sizes', 'span', 'src', 'srcdoc', 'srclang', 'srcset', 'start', 'step', 'summary', 'spellcheck', 'style', 'tabindex', 'target', 'title', 'type', 'translate', 'usemap', 'value', 'valign', 'width', 'wrap'],
    toolbarButtons: ['bold', 'italic', 'insertVideo', 'underline','paragraphFormat','align',
      'formatUL', 'formatOL','insertVideo', 'clearFormatting', 'indent',
      'insertLink', 'html', 'url'],
  })
</script>

app/views/posts/edit.html.erb
<div>
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
  <div>
    <% @posts.each do |post| %>
      <div class="border">
        <h2 class="text-muted"><%= link_to post.title, post %></h2>
        <h2 class="text-muted"><%= image_tag post.post_image_url(:thumb).to_s %></h2>
        <p class="wrap"><%=  post.body.truncate_words(15).html_safe %> <%= link_to '...Read more', post %></p>
        <p>Posted on <%= post.created_at.strftime("%B, %d, %Y")%></p>
      </div>
    <% end %>
    <%= will_paginate @posts %>
  </div>

app/views/posts/new.html.erb
<div class="page_wrapper">
  <h1>New Post</h1>
  <%= render 'form' %>
  <div class="froala-view">
    <%= simple_format(@post.body) %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="page_wrapper">
<h2><%= @post.title %></h2>
<h2><%= image_tag @post.post_image_url(:thumb).to_s %></h2>
<p>
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  <% if user_signed_in? %>
    | <%= link_to 'Edit?', edit_post_path(@post) %> |
      <%= link_to 'Delete?', post_path(@post), method: :delete, data: { confirm: 'Uh oh! Are you sure you would like to delete post?'} %>
  <% end %>
</p>
  <div class="froala-view">
    <%= @post.body.html_safe %>
  </div>


  <%= render 'disqus'%>

</div>